### ISSUE TITLE
type error with aom_image

### ISSUE THREAD

**Issue by asuper0** [rust-av/aom-rs#46]
With the same changes as #https://github.com/rust-av/vpx-rs/pull/42, I meet type error.

[here in encoder.rs](https://github.com/rust-av/aom-rs/blob/master/src/encoder.rs#L100-L102)
[here in decoder.rs](https://github.com/rust-av/aom-rs/blob/master/src/decoder.rs#L23-L25)

The rust think the fields cp, tc and mc in aom_image is i32, but the code assign them to u32.
I thought libaom changed their type at first, while aom-sys/cargo.toml require aom 3.0.0 but I have a 3.2.0. But I find the type are not changed between these two version just now. They keep enum type.
So I think the problem maybe caused by bindgen or other converting package, please check this:

[Cargo.lock](https://github.com/rust-av/aom-rs/files/9334798/Cargo.lock.txt)

**Comment by Luni-4** [comment]
Fixed in https://github.com/rust-av/aom-rs/commit/6381f14babf360e70b381ccea381353abbd95e98
