### ISSUE TITLE
Add travis support

### ISSUE THREAD

**Issue by lu-zero** [rust-av/aom-rs#7]
Similar to [rav1e](https://github.com/xiph/rav1e)'s requirements
- [ ] install nasm
- [ ] install cmake
- [ ] install perl
- [ ] use cargo

**Comment by the-pat** [comment]
Mind if I take this on?

**Comment by lu-zero** [comment]
Please do :)

**Comment by the-pat** [comment]
I am having trouble building the project.

When I run `cargo +nightly build` I get this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--static\" \"--libs\" \"--cflags\" \"aom\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package aom was not found in the pkg-config search path.\nPerhaps you should add the directory containing `aom.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'aom\' found\n" } }', libcore/result.rs:1009:5
```

Any thoughts?

**Comment by lu-zero** [comment]
You need to build `libaom` and make its `pkg-conf` file available by setting the environment variable.
See how it is done for [vpx-rs](https://github.com/rust-av/vpx-rs) and `libvpx`.

**Comment by the-pat** [comment]
@lu-zero, thank you! That was exactly what I needed.
